config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    get :manage, on: :collection
  end
  resources :blog_categories do
    get :manage, on: :collection
  end
  resources :blog_tags, only: [:index, :show]
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper
  include Slugable

  has_attached_file :image,
                    styles: BkBlog::Engine.config.blog_image_styles,
                    convert_options: BkBlog::Engine.config.blog_image_convert

  belongs_to :user
  belongs_to :blog_category
  has_many :blog_tag_refs
  has_many :blog_tags, through: :blog_tag_refs
  has_many :blog_attachments

  accepts_nested_attributes_for :blog_attachments, reject_if: :all_blank, allow_destroy: true

  scope :published, where({ published: true })

  scope :ordered, order('created_at DESC')

  default_scope ordered

  validates :full_text, :intro_text, :title, presence: true

  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png)

  def author
    user.try(:name) || 'Unknown'
  end
  def date
    created_at.strftime '%B %-d, %Y'
  end
  def short_intro
    short = strip_tags intro_text.to_html
    short.length > 100 ? short[0..99]+'...' : short
  end
  def tag_list=(names)
    self.blog_tags = names.split(',').reject {|n| n.strip.length < 1 }.map do |n|
      BlogTag.where(name: n.strip).first_or_create!
    end
  end
  def tag_list
    blog_tags.map(&:name).join ', '
  end
  def day
    created_at.day
  end
  def month
    Date::ABBR_MONTHNAMES[created_at.month]
  end
end

app/models/blog_attachment.rb
class BlogAttachment < ActiveRecord::Base
  has_attached_file :file

  belongs_to :blog

  before_save do
    self.title = file.original_filename if title.blank?
  end
end

app/models/blog_category.rb
class BlogCategory < ActiveRecord::Base
  include Slugable

  has_attached_file :image,
                    styles: BkBlog::Engine.config.blog_image_styles,
                    convert_options: BkBlog::Engine.config.blog_image_convert

  has_many :blogs

  scope :published, where(published: true)
  scope :greedy, includes(:blogs)

  validates :name, :description, presence: true

  # required for slugable to generate a slug automagically
  def title
    name
  end
end

app/models/blog_tag.rb
class BlogTag < ActiveRecord::Base
  has_many :blog_tag_refs
  has_many :blogs, through: :blog_tag_refs

  validates :name, presence: true

  before_create :create_slug

  scope :all_with_counts, select('blog_tags.*, count(blog_tag_refs.blog_id) as count').joins(:blog_tag_refs).order('blog_tags.name').group('blog_tags.id')

  def to_param
    slug
  end

  def create_slug
    self.slug = name.parameterize '_'
  end
end

app/models/blog_tag_ref.rb
class BlogTagRef < ActiveRecord::Base
  belongs_to :blog
  belongs_to :blog_tag
end

app/controllers/blog_categories_controller.rb
class BlogCategoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  def index
    @categories = BlogCategory.greedy
  end

  def show
    @category = BlogCategory.find_by_slug params[:id]
    @blogs = @category.blogs.paginate(page: params[:page], per_page: 10)
  end

  def new
    @category = BlogCategory.new
  end

  def create
    @category = BlogCategory.new blog_category_params
    if @category.save
      flash[:success] = 'Cateogry Created'
      redirect_to manage_blog_categories_path
    else
      render :new
    end
  end

  def edit
    @category = BlogCategory.find_by_slug params[:id]
  end

  def update
    @category = BlogCategory.find_by_slug params[:id]
    if @category.update_attributes blog_category_params
      flash[:success] = 'Cateogry Updated'
      redirect_to manage_blog_categories_path
    else
      render :edit
    end
  end

  def manage
    @categories = BlogCategory.all
  end

  def destroy
    category = BlogCategory.find_by_slug params[:id]
    category.destroy
    flash[:success] = 'Category Destroyed'
    redirect_to manage_blog_categories_path
  end

  private

  def blog_category_params
    params.require(:blog_category).permit :description, :name, :published, :image, :slug
  end
end

app/controllers/blog_tags_controller.rb
class BlogTagsController < ApplicationController
  respond_to :json
  def index
    @tags = BlogTag.all
    respond_with @tags
  end
  def show
    @tag = BlogTag.find_by_slug! params[:id]
    @blogs = @tag.blogs.page(params[:page])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def manage
    @blogs = Blog.paginate(page: params[:page], per_page: 50)
  end
  def new
    @blog = current_user.blogs.build
  end
  def create
    @blog = Blog.new blog_params
    if @blog.save
      flash[:success] = "Blog created"
      redirect_to manage_blogs_path
    else
      render :new
    end
  end
  def edit
    @blog = Blog.find_by_slug params[:id]
  end
  def update
    @blog = Blog.find_by_slug params[:id]
    if @blog.update_attributes blog_params
      flash[:success] = 'Blog Updated'
      redirect_to manage_blogs_path
    else
      render :edit
    end
  end
  def destroy
    blog = Blog.find_by_slug params[:id]
    blog.destroy
    flash[:success] = 'Blog destroyed'
    redirect_to manage_blogs_path
  end
  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 10)
  end
  def show
    @blog = Blog.find_by_slug params[:id]
  end

  private

  def blog_params
    params.require(:blog).permit :full_text, :intro_text, :title, :user_id, :created_at, :published, :image, :slug,
                                 :blog_category_id, :tag_list, {:blog_attachments_attributes => [:file, :title, :id]}
  end
end

app/helpers/blog_categories_helper.rb
module BlogCategoriesHelper
  def get_blog_categories
    BlogCategory.published
  end
end

app/helpers/blog_tags_helper.rb
module BlogTagsHelper
  def tag_list
    BlogTag.all_with_counts
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def recent_blog_posts
    posts = Blog.published.limit(3)
    render partial: 'blogs/small', collection: posts
  end
end

app/views/blog_categories/_error_messages.html.haml
- if @category.errors.any?
  %div{id: "error_explanation"}
    .alert.alert-error
      The form contains
      = pluralize(@category.errors.count, "error") + "."
    %ul
      - @category.errors.full_messages.each do |msg|
        %li
          *
          = msg

app/views/blog_categories/_form.html.haml
= form_for @category do |f|
  = render 'error_messages', object: f.object
  .row-fluid
    .span4
      %p
        = f.label :name
        = f.text_field :name
      %p
        = f.label :slug
        = f.text_field :slug
      %p
        = f.label :image
        = f.file_field :image
      %p
        = f.label :published
        = f.check_box :published
    .span8
      %p
        = f.label :description
        = f.text_area :description, style: 'width: 100%', rows: '20'
  .row-fluid
    .span12
      = f.submit f.object.new_record? ? 'Create Blog Category' : 'Update Blog Category'
      = link_to 'Cancel', manage_blog_categories_path
  .row-fluid
    .span8.offset4= render 'shared/markdown_key'

app/views/blog_categories/_manage.html.haml
%tr
  %td= manage.name
  %td= manage.published ? 'Yes' : 'No'
  %td
    = link_to 'Edit', edit_blog_category_path(manage), class: 'btn btn-small'
    = link_to 'Delete', manage, method: :delete, data: {confirm: "You Sure?"}, class: 'btn btn-small btn-danger'

app/views/blog_categories/edit.html.haml
.admin
  %h1 Edit Category
  = render 'form'

app/views/blog_categories/index.html.haml
<h1>BlogCategories#index</h1>
<p>Find me in app/views/blog_categories/index.html.erb</p>

app/views/blog_categories/manage.html.haml
.admin
  %h1 Manage Blog Categories
  %p= link_to 'New Category', new_blog_category_path, class: 'btn btn-primary'
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Name
        %th Published
        %th
    %tbody= render collection: @categories, partial: 'manage'

app/views/blog_categories/new.html.haml
.admin
  %h1 New Category
  = render 'form'

app/views/blog_categories/show.html.haml
%h1= @category.name
%p= @category.description
= render @blogs

app/views/blog_tags/show.html.haml
%h1= @tag.name
%hr
= render @blogs
%hr
= will_paginate @blogs

app/views/blogs/_blog.html.haml
- if blog.image.present?
  .blogimg= image_tag blog.image.url(:large)
%h2= blog.title
%p= blog.intro_text.to_html
= link_to 'Read More', blog, class: 'btn'
.clr
%hr

app/views/blogs/_error_messages.html.haml
- if @blog.errors.any?
  %div{id: "error_explanation"}
    .alert.alert-error
      The form contains
      = pluralize(@blog.errors.count, "error") + "."
    %ul
      - @blog.errors.full_messages.each do |msg|
        %li
          *
          = msg

app/views/blogs/_form.html.haml
:coffee
  $ ->
    split = ( val ) ->
      return val.split( /,\s*/ )
    extractLast = ( term ) ->
      return split( term ).pop()
    $('#blog_tag_list').bind( "keydown", ( ev ) ->
      if ( event.keyCode == $.ui.keyCode.TAB && $( this ).data( "ui-autocomplete" ).menu.active )
        event.preventDefault();
    ).autocomplete
      minLength: 0,
      source: (request, response) ->
        $.getJSON '#{blog_tags_path}', { term: extractLast( request.term ) }, (results) ->
          terms = new Array()
          for result in results
            terms.push(result.name)
          response terms
      focus: ->
        false
      select: ( event, ui ) ->
        terms = split( this.value )
        terms.pop()
        terms.push( ui.item.value )
        terms.push( "" )
        this.value = terms.join( ", " )
        return false

= form_for @blog do |f|
  = render 'error_messages', object: f.object
  .row-fluid
    .span4
      %p
        = f.label :title
        = f.text_field :title
      %p
        = f.label :slug
        = f.text_field :slug
      %p
        = f.label :tag_list
        = f.text_field :tag_list
      %p
        = f.label :blog_category_id
        = f.collection_select :blog_category_id, BlogCategory.all, :id, :name, prompt: 'select category'
      %p
        = f.label :user_id, 'Author'
        = f.collection_select :user_id, User.all, :id, :name, prompt: 'select author'
      %p
        = f.label :image
        = f.file_field :image
      %p
        = f.label :published
        = f.check_box :published
      %p
        = f.label :created_at
        = f.datetime_select :created_at
    .span8
      %p
        = f.label :intro_text
        = f.text_area :intro_text, style: 'width: 100%', rows: '5'
      %p
        = f.label :full_text
        = f.text_area :full_text, style: 'width: 100%', rows: '20'
      %h4 Attachments
      = f.fields_for :blog_attachments do |ff|
        %div{style: 'padding: 10px; margin-bottom: 10px; background-color: #f1f1f1;'}
          .row-fluid
            .span4
              = ff.label :title
              = ff.text_field :title
            .span3
              - if ff.object.persisted?
                = ff.label :_destroy, 'Delete?'
                = ff.check_box :_destroy
              - else
                = ff.label :file
                = ff.file_field :file
  .row-fluid
    .span12
      = f.submit f.object.new_record? ? 'Create Blog' : 'Update Blog'
      = link_to 'Cancel', manage_blogs_path
  .row-fluid
    .span8.offset4= render 'shared/markdown_key'

app/views/blogs/_manage.html.haml
%tr
  %td= manage.title
  %td= manage.author
  %td= manage.created_at
  %td= manage.published ? 'Yes' : 'No'
  %td
    = link_to 'Edit', edit_blog_path(manage), class: 'btn btn-small'
    = link_to 'Delete', manage, method: :delete, data: {confirm: "You Sure?"}, class: 'btn btn-small btn-danger'

app/views/blogs/_sidebar.html.haml
.blogs
  = render partial: 'blogs/small', collection: sidebar
  = link_to 'View More Blog Posts', blogs_path, class: 'btn'

app/views/blogs/_small.html.haml
.item
  - if small.image.exists?
    .blogimg
      = image_tag small.image.url(:small)
  .body{class: small.image.exists? ? 'offset': ''}
    %h4= link_to small.title, small
    %p= small.short_intro

app/views/blogs/edit.html.haml
.admin
  %h1 Edit Blog
  = render 'form'

app/views/blogs/index.html.haml
%h1 Welcome to the blog!
%hr
= render @blogs
%hr
= will_paginate @blogs

app/views/blogs/manage.html.haml
.admin
  %h1 Manage Blog
  %p= link_to 'New Blog', new_blog_path, class: 'btn btn-primary'
  %p= will_paginate @blogs
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Title
        %th Author
        %th Created
        %th Published
        %th
    %tbody= render collection: @blogs, partial: 'blogs/manage'
  %p= will_paginate @blogs

app/views/blogs/new.html.haml
.admin
  %h1 New Blog
  = render 'form'

app/views/blogs/show.html.haml
%h1= @blog.title
%p
  %em= "Date: #{@blog.date}"
- if @blog.image.present?
  .blogimg= image_tag @blog.image.url(:large)
.lead= @blog.intro_text.to_html
.full= @blog.full_text.to_html
.clr

app/views/shared/_markdown_key.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Enter this
      %th Get this
  %tbody
    %tr
      %td # Header 1
      %td
        %h1 Header 1
    %tr
      %td ## Header 2
      %td
        %h2 Header 2
    %tr
      %td ### Header 3
      %td
        %h3 Header 3
    %tr
      %td #### Header 4
      %td
        %h4 Header 4
    %tr
      %td this is **bold**
      %td
        this is
        %b bold
    %tr
      %td needs *emphasis*
      %td
        needs
        %em emphasis
    %tr
      %td
        * Items
        %br
        * In
        %br
        * A
        %br
        * List
      %td
        %ul
          %li Items
          %li In
          %li A
          %li List
    %tr
      %td
        [click this link](http://www.example.com)
        %br
        = "- or -"
        %br
        [_click this link (new window)](http://www.example.com)
        %br
        = "- or -"
        %br
        http://www.example.com
      %td
        = link_to 'click this link', 'http://www.example.com'
        %br
        = "- or -"
        %br
        = link_to 'click this link (new window)', 'http://www.example.com', target: '_blank'
        %br
        = "- or -"
        %br
        = link_to 'http://www.example.com', 'http://www.example.com'